version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "requirements.txt" }}
      - run:
          name: Install Dependencies
          command: |
            python -m venv venv
            export PYTHONPATH=":$(pwd)"
            . venv/bin/activate
            pip install -r requirements.txt
            echo $PYTHONPATH
      - save_cache:
          key: v1-deps-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            pytest tests/ -v
      - run:
          name: Run Content Team
          command: |
            . venv/bin/activate
            python -m content_team.agents
    environment:
      OPENAI_API_KEY: $OPENAI_API_KEY
      OPENAI_MODEL: openai/gpt-4

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
